services:
  python-api:
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
      - PORT=8000
      - DATABASE_URL=your_azure_sql_connection_string
    ports:
      - "8000:8000"
    restart: always

  budibase:
    image: budibase/budibase:latest
    environment:
      - PORT=8080
    ports:
      - "8080:8080"
    restart: always

  sidecar:
    image: your_sidecar_image_source_here  # Replace with your actual sidecar image
    environment:
      - SIDE_SETTING=default_value  # Adjust environment variables as needed
    restart: always
