services:
  python-api:
    image: witwolfvic/python-api:latest
    environment:
      - PORT=8000
      - DATABASE_URL=mssql://CloudSAe8df3302:${DB_PASSWORD}@nexum.database.windows.net:1433/Nexum?encrypt=true&trustServerCertificate=false&connection_timeout=30
      - WEBSITE_HOSTNAME=nexumai.azurewebsites.net
      - WEBSITES_ENABLE_APP_SERVICE_STORAGE=false
      - WEBSITE_SITE_NAME=NexumAI
      - WEBSITE_AUTH_ENABLED=False
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: always

  budibase:
    image: witwolfvic/budibase:latest
    environment:
      - PORT=8080
      - DB_TYPE=sql
      - DB_DRIVER=mssql
      - DB_URL=nexum.database.windows.net
      - DB_PORT=1433
      - DB_NAME=Nexum
      - DB_USER=CloudSAe8df3302
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_SSL=true
      - NODE_ENV=production
      - WEBSITE_HOSTNAME=nexumai.azurewebsites.net
      - WEBSITES_ENABLE_APP_SERVICE_STORAGE=false
      - WEBSITE_SITE_NAME=NexumAI
      - WEBSITE_AUTH_ENABLED=False
      - BUDIBASE_ENVIRONMENT=PRODUCTION
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: always
