services:
  python-api:
    image: witwolfvic/python-api:latest  # Ensure this is all lowercase
    environment:
      - PORT=8000
      - DATABASE_URL=your_actual_azure_sql_connection_string  # Replace with your actual Azure SQL connection string
    ports:
      - "8000:8000"
    restart: always

  budibase:
    image: witwolfvic/budibase:latest  # Ensure this is all lowercase
    environment:
      - PORT=8080
    ports:
      - "8080:8080"
    restart: always
