services:
  python-api:
    image: witwolfvic/python-api:latest
    environment:
      - PORT=8000
      - DATABASE_URL=mssql://CloudSAe8df3302:${DB_PASSWORD}@nexum.database.windows.net:1433/Nexum?encrypt=true&trustServerCertificate=false&connection_timeout=30
      - WEBSITE_HOSTNAME=nexumai.azurewebsites.net
      - WEBSITES_ENABLE_APP_SERVICE_STORAGE=false
      - WEBSITE_SITE_NAME=NexumAI
      - WEBSITE_AUTH_ENABLED=False
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: always

  budibase:
    image: witwolfvic/budibase:latest
    environment:
      - PORT=8080
      - DISABLE_COUCH_DB=true
      - SQL_CONNECTION_STRING=Server=tcp:nexum.database.windows.net,1433;Initial Catalog=Nexum;Persist Security Info=False;User ID=CloudSAe8df3302;Password=${DB_PASSWORD};MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30
      - SQL_TYPE=mssql
      - NODE_ENV=production
      - SELF_HOSTED=1
      - JWT_SECRET=${JWT_SECRET}
      - PLATFORM_URL=http://localhost:8080
      - WORKER_URL=http://localhost:8080
      - MINIO_ENABLED=false
      - REDIS_ENABLED=false
      - CLUSTER_MODE=false
      - WEBSITES_ENABLE_APP_SERVICE_STORAGE=false
      - WEBSITE_SITE_NAME=NexumAI
      - WEBSITE_AUTH_ENABLED=False
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: always
