services:
  python-api:
    image: witwolfvic/python-api:latest
    environment:
      - PORT=8000
      - DATABASE_URL=mssql://CloudSAe8df3302:${DB_PASSWORD}@nexum.database.windows.net:1433/Nexum?encrypt=true&trustServerCertificate=false&connection_timeout=30
    ports:
      - "8000:8000"
    restart: always

  budibase:
    image: witwolfvic/budibase:latest
    environment:
      - PORT=8080
      - DB_TYPE=sql
      - DB_DRIVER=mssql
      - DB_URL=nexum.database.windows.net
      - DB_PORT=1433
      - DB_NAME=Nexum
      - DB_USER=CloudSAe8df3302
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_SSL=true
      - NODE_ENV=production
    ports:
      - "8080:8080"
    restart: always
